### ISSUE TITLE
This isn't really an issue, this is just a question.

### ISSUE THREAD

**Issue by Rxplicat3dStxr4ge** [floatzeI/2016-roblox#12]
Will you make a 2013 version out of this?

**Comment by floatzeI** [comment]
I don't plan to.

**Comment by Rxplicat3dStxr4ge** [comment]
Oh, but i can't seem to install the 2012 version of this.

**Comment by floatzeI** [comment]
Unfortunately I'm aware that the 2012 site doesn't work for most people. I don't have time to fix it right now, but if anyone wanted to, they should probably just convert all the TSED code to express (or upgrade everything to TSED 6 - but this isn't really ideal since the project would probably just run into more issues in the future).

**Comment by Rxplicat3dStxr4ge** [comment]
How do i do that? and also i can't seem to clone the repo.

**Comment by Rxplicat3dStxr4ge** [comment]
> Unfortunately I'm aware that the 2012 site doesn't work for most people. I don't have time to fix it right now, but if anyone wanted to, they should probably just convert all the TSED code to express (or upgrade everything to TSED 6 - but this isn't really ideal since the project would probably just run into more issues in the future).

i managed to clone the repo, but idk how to convert the TSED code to express.

**Comment by Rxplicat3dStxr4ge** [comment]
please make a 2013 versio-
